from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views
from .forms import (
    DefinirNovaSenhaForm,
    RecuperacaoSenhaForm,
)


urlpatterns = [
    path(
        '',
        views.login_view,
        name='login'
    ),
    path(
        'sair/',
        views.logout_view,
        name='logout'
    ),
    path(
        'cadastro/docente/',
        views.cadastrar_docente,
        name='cadastrar_docente'
    ),
    path(
        'dashboard/',
        views.dashboard,
        name='dashboard'
    ),
    path(
        'bancas/',
        views.visualizar_bancas,
        name='visualizar_bancas'
    ),
    path(
        'solicitar/',
        views.solicitar_banca,
        name='solicitar_banca'
    ),
    path(
        'cadastrar/aluno/',
        views.cadastrar_aluno,
        name='cadastrar_aluno'
    ),
    path(
        'cadastrar/projeto/',
        views.cadastrar_projeto,
        name='cadastrar_projeto'
    ),
    path(
        'avaliar/<int:solicitacao_id>/',
        views.avaliar_solicitacao,
        name='avaliar_solicitacao'
    ),
    path(
        'meus-tccs/',
        views.meus_tccs,
        name='meus_tccs'
    ),
    path(
        'pesquisar/',
        views.pesquisar,
        name='pesquisar'
    ),
    path(
        'documentos/',
        views.documentos,
        name='documentos'
    ),
    path(
        'documentos/<int:modelo_id>/download/',
        views.baixar_documento,
        name='baixar_documento'
    ),
    path(
        'documentos/banca/<int:solicitacao_id>/pdf/',
        views.gerar_pdf_banca,
        name='gerar_pdf_banca'
    ),
    path(
        'espacos/',
        views.gerenciar_espacos,
        name='gerenciar_espacos'
    ),
    path(
        'espacos/<int:espaco_id>/editar/',
        views.editar_espaco,
        name='editar_espaco'
    ),
    path(
        'espacos/<int:espaco_id>/status/',
        views.alternar_status_espaco,
        name='alternar_status_espaco'
    ),
    path(
        'disponibilidades/<int:disponibilidade_id>/editar/',
        views.editar_disponibilidade,
        name='editar_disponibilidade'
    ),
    path(
        'disponibilidades/<int:disponibilidade_id>/status/',
        views.alternar_status_disponibilidade,
        name='alternar_status_disponibilidade'
    ),
    path(
        'coordenacao/solicitacoes/',
        views.solicitacoes_coordenacao,
        name='solicitacoes_coordenacao'
    ),
    path(
        'solicitacoes/<int:solicitacao_id>/arquivo-tcc/',
        views.baixar_tcc_solicitacao,
        name='baixar_tcc_solicitacao'
    ),
    path(
        'coordenacao/solicitacoes/<int:solicitacao_id>/editar/',
        views.editar_solicitacao_coordenacao,
        name='editar_solicitacao_coordenacao'
    ),
    path(
        'cadastro/docente/confirmar/<uidb64>/<token>/',
        views.confirmar_email_docente,
        name='confirmar_email_docente'
    ),
    path(
        'cadastro/docente/reenviar-confirmacao/',
        views.reenviar_confirmacao_docente,
        name='reenviar_confirmacao_docente'
    ),
        path(
        'senha/recuperar/',
        auth_views.PasswordResetView.as_view(
            template_name='recuperar_senha.html',
            form_class=RecuperacaoSenhaForm,
            email_template_name=(
                'emails/recuperacao_senha.txt'
            ),
            html_email_template_name=(
                'emails/recuperacao_senha.html'
            ),
            subject_template_name=(
                'emails/recuperacao_senha_assunto.txt'
            ),
            success_url=reverse_lazy(
                'recuperar_senha_enviada'
            ),
        ),
        name='recuperar_senha'
    ),
    path(
        'senha/recuperar/enviado/',
        auth_views.PasswordResetDoneView.as_view(
            template_name=(
                'recuperar_senha_enviada.html'
            ),
        ),
        name='recuperar_senha_enviada'
    ),
    path(
        'senha/redefinir/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='redefinir_senha.html',
            form_class=DefinirNovaSenhaForm,
            success_url=reverse_lazy(
                'redefinir_senha_concluida'
            ),
        ),
        name='redefinir_senha'
    ),
    path(
        'senha/redefinir/concluida/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name=(
                'redefinir_senha_concluida.html'
            ),
        ),
        name='redefinir_senha_concluida'
    ),
        path(
        'solicitacoes/<int:solicitacao_id>/',
        views.detalhar_solicitacao,
        name='detalhar_solicitacao'
    ),
    path(
        'meu-perfil/',
        views.meu_perfil,
        name='meu_perfil'
    ),
    path(
        'bancas/<int:banca_id>/registrar-nota/',
        views.registrar_nota_banca,
        name='registrar_nota_banca'
    ),
]