# Generated by Django 6.0.6 on 2026-07-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_inicio', models.DateTimeField()),
                ('data_horario_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.bancatcc')),
            ],
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bancasapp.espacofisico'),
        ),
        migrations.CreateModel(
            name='ProjetoTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('semestre_letivo', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('EM_ANÁLISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADA', 'Recusada')], default='EM_ANÁLISE', max_length=15)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.discente')),
            ],
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='projeto_tcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.projetotcc'),
        ),
        migrations.CreateModel(
            name='pUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('COORDENACAO', 'Coordenação'), ('DOCENTE', 'Docente')], max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembroBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ORIENTADOR', 'Orientador'), ('AVALIADOR', 'Avaliador')], max_length=15)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.bancatcc')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.pusuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_data_inicio', models.DateTimeField()),
                ('opcao_data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('EM_ANÁLISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='EM_ANÁLISE', max_length=15)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.espacofisico')),
                ('projeto_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.projetotcc')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.pusuario')),
            ],
        ),
    ]
