# Generated by Django 6.0.6 on 2026-08-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_avaliador_externo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Avaliador Externo')),
                ('instituicao_avaliador_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição Externa')),
                ('avaliador_interno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancas_avaliador_interno', to='bancasapp.pusuario', verbose_name='Avaliador Interno (UFAC)')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancas_orientador', to='bancasapp.pusuario', verbose_name='Professor Orientador')),
                ('projeto_tcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.projetotcc', verbose_name='Projeto de TCC')),
            ],
        ),
    ]
