# Generated by Django 6.0.6 on 2026-08-18 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0003_modelodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='data_decisao',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='data_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='decidida_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_decididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='motivo_decisao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='bancasapp.pusuario'),
        ),
    ]
