# Generated by Django 6.0.6 on 2026-08-18 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0004_solicitacaoagendamento_data_decisao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacofisico',
            options={'ordering': ['nome'], 'verbose_name': 'Espaço físico', 'verbose_name_plural': 'Espaços físicos'},
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancasapp.espacofisico'),
        ),
        migrations.CreateModel(
            name='DisponibilidadeEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e hora de início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data e hora de término')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='bancasapp.espacofisico')),
            ],
            options={
                'verbose_name': 'Disponibilidade de espaço',
                'verbose_name_plural': 'Disponibilidades de espaços',
                'ordering': ['data_hora_inicio', 'espaco__nome'],
                'indexes': [models.Index(fields=['espaco', 'data_hora_inicio', 'data_hora_fim'], name='disp_espaco_periodo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='disponibilidade_fim_apos_inicio')],
            },
        ),
    ]
