# Generated by Django 6.0.6 on 2026-08-23 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0005_alter_espacofisico_options_espacofisico_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaobanca',
            name='coorientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bancas_coorientador', to='bancasapp.pusuario', verbose_name='Professor Coorientador'),
        ),
        migrations.AddField(
            model_name='composicaobanca',
            name='segundo_avaliador_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bancas_segundo_avaliador_interno', to='bancasapp.pusuario', verbose_name='Segundo Avaliador Interno (UFAC)'),
        ),
        migrations.AddField(
            model_name='composicaobanca',
            name='solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composicao_banca', to='bancasapp.solicitacaoagendamento', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='solicitacaoagendamento',
            name='arquivo_tcc',
            field=models.FileField(blank=True, upload_to='tcc/solicitacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo do TCC'),
        ),
        migrations.AlterField(
            model_name='composicaobanca',
            name='projeto_tcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancasapp.projetotcc', verbose_name='Projeto de TCC'),
        ),
    ]
