# Generated by Django 6.0.6 on 2026-08-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0007_vincular_composicoes_solicitacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='status',
            field=models.CharField(choices=[('EM_ANÁLISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('EXPIRADA', 'Expirada')], default='EM_ANÁLISE', max_length=15),
        ),
    ]
