# Generated by Django 6.0.6 on 2026-08-24 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0008_alter_solicitacaoagendamento_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pusuario',
            name='analisado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_docentes_analisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pusuario',
            name='data_analise',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pusuario',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='pusuario',
            name='motivo_analise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pusuario',
            name='status_cadastro',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='APROVADO', max_length=10, verbose_name='Situação do cadastro'),
        ),
    ]
