# Generated by Django 6.0.6 on 2026-08-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0009_pusuario_analisado_por_pusuario_data_analise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pusuario',
            name='analisado_por',
        ),
        migrations.RemoveField(
            model_name='pusuario',
            name='data_analise',
        ),
        migrations.RemoveField(
            model_name='pusuario',
            name='motivo_analise',
        ),
        migrations.RemoveField(
            model_name='pusuario',
            name='status_cadastro',
        ),
        migrations.AddField(
            model_name='pusuario',
            name='data_confirmacao_email',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de confirmação do e-mail'),
        ),
    ]
