# Generated by Django 6.0.6 on 2026-08-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0010_remove_pusuario_analisado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaobanca',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bancas_presididas', to='bancasapp.pusuario', verbose_name='Presidente da banca'),
        ),
    ]
