# Generated by Django 6.0.6 on 2026-08-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0011_composicaobanca_presidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pusuario',
            name='titulacao',
            field=models.CharField(blank=True, choices=[('PROF', 'Prof.'), ('PROFA', 'Profa.'), ('PROF_ESP', 'Prof. Esp.'), ('PROFA_ESP', 'Profa. Esp.'), ('PROF_ME', 'Prof. Me.'), ('PROFA_MA', 'Profa. Ma.'), ('PROF_DR', 'Prof. Dr.'), ('PROFA_DRA', 'Profa. Dra.')], default='', max_length=12, verbose_name='Titulação acadêmica'),
        ),
    ]
