# Generated by Django 6.0.6 on 2026-08-26 06:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0013_composicaobanca_titulacao_avaliador_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bancatcc',
            name='data_registro_nota',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='nota_registrada_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_de_bancas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banca_tcc', to='bancasapp.solicitacaoagendamento', verbose_name='Solicitação aprovada'),
        ),
        migrations.AddField(
            model_name='bancatcc',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('AGUARDANDO_NOTA', 'Aguardando nota'), ('FINALIZADA', 'Finalizada')], default='AGENDADA', max_length=20),
        ),
    ]
