# Generated by Django 6.0.6 on 2026-09-07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0014_bancatcc_data_registro_nota_bancatcc_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaAcesso',
            fields=[
                (
                    'chave',
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'escopo',
                    models.CharField(
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    'quantidade',
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                    ),
                ),
                (
                    'inicio_janela',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    'bloqueado_ate',
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    'atualizado_em',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tentativa de acesso',
                'verbose_name_plural': 'Tentativas de acesso',
            },
        ),
    ]
