# Generated by Django 6.0.8 on 2026-09-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancasapp', '0015_tentativaacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaobanca',
            name='avaliador_interno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancas_avaliador_interno', to='bancasapp.pusuario', verbose_name='Primeiro Avaliador Interno (UFAC)'),
        ),
        migrations.AlterField(
            model_name='composicaobanca',
            name='segundo_avaliador_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bancas_segundo_avaliador_interno', to='bancasapp.pusuario', verbose_name='Segundo Avaliador Interno (UFAC)'),
        ),
    ]
